# Generated by Django 2.1.5 on 2019-01-19 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название')),
            ],
            options={
                'verbose_name': 'тип контейнера',
                'verbose_name_plural': 'типы контейнеров',
            },
        ),
        migrations.CreateModel(
            name='FreeContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True, verbose_name='адрес')),
                ('count', models.PositiveIntegerField(verbose_name='количество')),
                ('parts', models.BooleanField(default=True, verbose_name='можно частями')),
                ('date_from', models.DateField(verbose_name='свободны с')),
                ('date_till', models.DateField(blank=True, null=True, verbose_name='свободны до')),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.Station', verbose_name='располжене')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boxes.ContainerType', verbose_name='тип')),
            ],
            options={
                'verbose_name': 'тип контейнера',
                'verbose_name_plural': 'типы контейнеров',
            },
        ),
        migrations.CreateModel(
            name='NeededContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True, verbose_name='адрес')),
                ('count', models.PositiveIntegerField(verbose_name='количество')),
                ('date_from', models.DateField(verbose_name='свободны с')),
                ('date_till', models.DateField(blank=True, null=True, verbose_name='свободны до')),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.Station', verbose_name='располжене')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boxes.ContainerType', verbose_name='тип')),
            ],
            options={
                'verbose_name': 'тип контейнера',
                'verbose_name_plural': 'типы контейнеров',
            },
        ),
    ]
