# Generated by Django 2.1.5 on 2019-01-19 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freecontainer',
            options={'verbose_name': 'свободный контейнер', 'verbose_name_plural': 'свободные контейнеры'},
        ),
        migrations.AlterModelOptions(
            name='neededcontainer',
            options={'verbose_name': 'искомый контейнер', 'verbose_name_plural': 'искомые контейнеры'},
        ),
    ]
