# Generated by Django 2.1.5 on 2019-01-23 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0002_auto_20190119_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freecontainer',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.Station', verbose_name='расположение'),
        ),
        migrations.AlterField(
            model_name='neededcontainer',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.Station', verbose_name='расположение'),
        ),
    ]
