# Generated by Django 2.1.5 on 2019-02-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0003_auto_20190123_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='freecontainer',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='цена'),
        ),
    ]
