# Generated by Django 2.1.5 on 2019-09-20 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0005_auto_20190208_1003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freecontainer',
            old_name='contact',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='neededcontainer',
            old_name='contact',
            new_name='owner',
        ),
    ]
