# Generated by Django 2.1.5 on 2019-09-21 17:43
from faker import Faker
from faker.providers import profile

from django.db import migrations


def init_data(apps, schema_editor):
    fake = Faker()
    fake.add_provider(profile)
    users_set = set()
    email_set = set()
    users = []
    User = apps.get_model('core', 'User')
    while len(users_set) < 10:
        user = fake.profile(fields=['username', 'mail'])
        if (user['username'] not in users_set) and (user['mail'] not in email_set):
            users_set.add(user['username'])
            email_set.add(user['mail'])
            users.append(User(username=user['username'], email=user['mail']))
    User.objects.bulk_create(users)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(init_data),
    ]
