# Generated by Django 2.1.5 on 2019-01-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freecontainerrequest',
            name='active',
            field=models.BooleanField(default=True, verbose_name='активен'),
        ),
    ]
