# Generated by Django 2.1.5 on 2019-02-02 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searches', '0003_auto_20190130_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freecontainerrequest',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
