# Generated by Django 2.1.5 on 2019-09-20 23:35

from django.db import migrations


def init_data(apps, schema_editor):
    Region = apps.get_model('geo', 'Region')
    City = apps.get_model('geo', 'City')
    Station = apps.get_model('geo', 'Station')
    Region.objects.bulk_create([
        Region(title='Москва'),
        Region(title='Санкт-Петербург'),
        Region(title='Нижегородская область'),
        Region(title='Коми республика'),
    ])
    City.objects.bulk_create([
        City(title='Москва', region=Region.objects.get(title='Москва')),
        City(title='Санкт-Петербург', region=Region.objects.get(title='Санкт-Петербург')),
        City(title='Нижний Новгород', region=Region.objects.get(title='Нижегородская область')),
        City(title='Сыктывкар', region=Region.objects.get(title='Коми республика')),
        City(title='Ухта', region=Region.objects.get(title='Коми республика')),
    ])
    Station.objects.bulk_create([
        Station(title='Казанский', city=City.objects.get(title='Москва')),
        Station(title='Ярославский', city=City.objects.get(title='Москва')),
        Station(title='Ленинградский', city=City.objects.get(title='Москва')),
        Station(title='Павелецкий', city=City.objects.get(title='Москва')),
        Station(title='Московский', city=City.objects.get(title='Санкт-Петербург')),
        Station(title='Московский', city=City.objects.get(title='Нижний Новгород')),
        Station(title='Сыктывкар', city=City.objects.get(title='Сыктывкар')),
        Station(title='Ухта', city=City.objects.get(title='Ухта')),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_auto_20190123_1757'),
    ]

    operations = [
        migrations.RunPython(init_data),
    ]
